### ISSUE TITLE
chance accent color unconnected to main accent?

### ISSUE THREAD

**Issue by incantatem1** [Spekulucius/obsidian-brainhack#1]
i don't want to change my main accent, please

**Comment by Spekulucius** [comment]
Hey, thanks for the feedback :)
As far as I understand, you want to change the overall theme's color without changing your accent color set in the "appearance" tab.

Tbh, I don't really understand why you would want to do that, can you please elaborate further?
Do you want to keep the button color, the selection color etc. to your accent color, or do you just don't want to change your accent color in general?

All in all, this change would only be possible with the "style settings" plugin, which I don't plan to incorporate - as it is stated in the plugin description "I made this theme (mainly for myself), because I like to adjust the look of Obsidian on a regular basis. However, it needed adjusting more than one variable, to get everything going.".

If there is a specific advantage you would gain from separating the main accent color from the theme's colors, please let me know so I can understand your issue - maybe I'll find a way to include your request - even if it means publishing a second alternative theme with more customization options.

As of now, changing the accent color is quite limited, as it is directly connected to the main accent color you set in the "appearance" tab - to change this, i would need to change a lot of variables, meaning a general restructure of the code, which would lead to losing the convenience of changing the theme's look "on the fly".

But as I said, please let me know about your issue in detail, so I can see what I can do.

**Comment by incantatem1** [comment]
i want to do that because i use multiple themes and in some the main accent color i use looks better than what i want to do with brainhack. i don't want to change it constantly when i switch between different themes.

**Comment by Spekulucius** [comment]
I see - unfortunately, I wont incorporate a color option besides the accent color. But if you want, I can provide a CSS snipped that overrides the colors, and maybe even (depending on how much spare time I got) be accessible within the "style settings" plugin.

Would something like this resolve your issue?

Besides, thank you for trying out my theme!

**Comment by incantatem1** [comment]
yes, that would be great. thank you
