### ISSUE TITLE
general feedback: "Where is the css code?"

### ISSUE THREAD

**Issue by DutchPete** [Spekulucius/obsidian-brainhack#2]
I opened the `theme.css` file and found only about 5 lines related to macOS. Where can I the rest?

**Comment by Spekulucius** [comment]
Hi! First of all, thanks for using my theme.
To address your issue in an effective way, I'd ask you to provide more information about your issue, what it is regarding etc..

If you are mainly looking for code-lines regarding MACOS, you are right, there are not that many, mainly because there are not needed based on my testing (tested on MACOS 14).

So, if you encountered a problem on MACOS regarding missing code (specific for MACOS), please let me know.

In addition, a question: Why did you search specific code for MACOS? If you could clarify this, it would be more efficient regarding the detection of the core issue.

Thanks for your feedback!

**Comment by DutchPete** [comment]
You misunderstood me.

When I use a new theme, there are almost invariably a few things that I want to change, and sometimes I need to check the theme's css to see what I need to change or how the author did something because my css amendment does not work.

So, for example, I am using LXGW WenKai as my body text font. I love that font, but in other themes, bold, as in `**bold**`, is hardly distinguishable from non-bold, so I used a color to accentuate bold text.

In Brainhack, however, I was surprised to see that bold IS distinguishable, probably because non-bold, i.e. regular/normal text is slightly thinner. So, I was wondering how that is possible.

I was also wondering how it works that with just a change in accent color everything else changes.

When I checked your theme file, there are just 16 lines, all related macOS. I am not on macOS but on Linux, LMDE to be precise.

I noticed that you avoided answering my question so I suspect your worried I might have a hidden agenda.

NOTE: I AM NOT ASKING THESE QUESTIONS TO STEAL YOUR IDEAS — I don't make my own themes, I am happy to use others' themes.

**Comment by Spekulucius** [comment]
Thanks for the detailed feedback.
First of all, I didn't suspect anything, I just had a hard time figuring the root of your issue to address it more specifically, which you did (and I'm very thankful for that) - so, no need to worry :)
(Also, as per license, you could do what you want with my theme, It wouldn't be a problem - rather, I'm really glad that I can inspire other people / give something to them)

For your question regarding bold text, it is really simple: i just didn't change any variables regarding bold text, so it is quite vanilla. But yes, I changed the font weight of the default text -> just search "weight" in my code, you should find it pretty easily.

***

The accent color thing is quite funny: the color you set in the appearance tab gets stored as hsl -> each one has a specific variable 
(--accent-h), (--accent-s), (--accent-l): using calc(), I modified those values and created variables, that use them, for example:
`--accent-color-test: var(accent-h), calc(.5*(var-accent-s)), var(--accent-l);`

If you have any more feedback or additions, please let me know :)

**Comment by DutchPete** [comment]
Where can I see all that? Like I say, there is nothing in the `theme.css`, so where is all the css code that defines your theme? This all there is in `theme.css`

![image](https://github.com/user-attachments/assets/04a4d47f-f28b-4fc5-b910-9f889f57809b)

**Comment by Spekulucius** [comment]
Okay, just to narrow it down: did you confirm, that this is all the code you have in the theme.css file? There should be about 2000 lines with about 1000 lines of code - they are spaced for better navigation.

**Comment by DutchPete** [comment]
Silly me, now I see it. There is a gap of 23 lines between the last line in the screenshot above and the next line. That does not sound like a lot, but when you open the `theme.css` fileyou only see what is in that screenshot.

However, logic should have told me to scroll down, but unfortunately it did not, as a result of which I have made a fool of myself.

I offer you my sincere apologies for this really stupid oversight.
Thanks for a nice theme!

Sporting a now red face in shame I'll close this issue.

**Comment by Spekulucius** [comment]
Hi, first of all, not a problem at all, although I'm glad it just was human error and not a mistake in my code :)

hijacking this to ask you for feedback (if you want to, obviously): can you tell me, what convinced you to download Brainhack? What do you like, and more importantly, what don't you like? Do you have any suggestions for Brainhack? And do you use it mainly, or switch between themes? If so, why?
(Please don't feel pressured to answer, but it would help me improving my theme!)

Have a great day!

**Comment by DutchPete** [comment]
I am happy to provide you with feedback.

> what convinced you to download Brainhack?

I liked what I read and saw on your [Github page](https://github.com/Spekulucius/obsidian-brainhack). Believe it or not, but the *lighter font weight* intrigued me because of what I described above.

> What do you like?

I like all of it.

> what don't you like?

I don't like:
* I cannot get the blockquotes like you show on your Github page. Mine are like this:

![image](https://github.com/user-attachments/assets/a7e16a82-0208-47dd-8437-e2d356584937)

* an embedded blockquote is partially right:

![image](https://github.com/user-attachments/assets/d553ddce-7e28-4ada-b73f-1a82b24e3e4a)

* I cannot get a listed blockquote: if I put a dash (`-`) in front of the `>` of a blockquote, it is not rendered in blockquote format like on your Github page, So, an indented listed blockquote does not work either:

![image](https://github.com/user-attachments/assets/25bc20a6-b560-4ce3-8221-b755883a7a6c)

* in a call-out the collapse arrow is not aligned with the text:

![image](https://github.com/user-attachments/assets/63763ddb-7efb-4ac6-aef1-d51b468d2145)

* I don't get the "sweet shadows" you mention, e.g. see Order of the Garter call-out above.

* I don't like images in grey scale at all, I prefer color images. A toggle in Style Settings would be great.

**Comment by DutchPete** [comment]
Forgot to answer your last questions:

> And do you use it mainly, or switch between themes?

I have installed it as my main theme. Of course, it is early days yet so I need to evaluate how it performs and if I continue to like it. I would like to continue to use it.

> Do you have any suggestions for Brainhack?

Style Settings is very useful, I referred to it above. You could make some features optional/togglable. 1 caveat: don't offer too much in SS because then it becomes overwhelming — IMO some themes go overboard with it.

**Comment by Spekulucius** [comment]
Thank you very much for your contribution!
+ the blockquotes, as of now, are only rendered correctly in reading mode. I plan of getting this feature into preview mode, shouldn't be that much work.
 + as of now, blockquotes in preview mode do render without style, as you already noticed
 + I'm planning to incorporate this into update 1.4, wich should release in a couple days

+ to make a listed blockquote (as far as I know, thats how I'm doing it), is to make a list marker (+ or -), and put the blockquote in the line below - press enter + shift so the (+,-) won't disappear.

+ I don't use the collapse feature at all, so it would be a thing to look into that. Thats a thing that flew below my radar, thanks for pointing that out!

+ Regarding "sweet shadows", it means that (for example) callouts should have a shadow surrounding them, as well as blockquotes etc. 
 + maybe it is, because you have them collapsed, have to look into that

thats how it looks in my side:
<img width="1219" alt="Screenshot 2024-07-25 at 13 27 20" src="https://github.com/user-attachments/assets/fc26b582-723b-4538-aeac-c7b803ae92e1">


+ Regarding greyscale images, I knew it would be a risky move to incorporate this feature without the ability to change. I'm currently working on a "style settings" implementation, to, as you proposed, toggle it off

Another user pointed out, that they don't want to change their accent color to change the theme's colors, so I'm also working on an override on that.

**But: I don't like depending on style settings at all.** I used the minimal theme until now, but (as it states in my theme's description), I wanted to make a theme that works perfectly out of the box, without needing to change anything or without installing a separate plugin - so the settings, if being incorporated into 1.4, that will be available in the style settings plugin, will be simple overrides for features one doesn't want to use, i.e. grayscale images, color override, etc.

If you have any more to say, hit me up or create another issue - maybe I'll open a seperate thread for proposes, but as of now, there aren't that many users so I don't want to overcomplicate things.

**Comment by Spekulucius** [comment]
To fix your issue with greyscale images until I update a style settings implementation, I uploaded a snipped to my repo, you can find it under "overrides"!

**Comment by DutchPete** [comment]
Sounds good, looking forward to 1.4.
I understand your reasoning about Style Settings, and I don't want to interfere with that. After all, it is your theme 😀

Sweet shadows: yes, they are there. They are very subtle so I missed them.

Regarding the anti-grey scale snippet, many thanks for making it available. I looked [here](https://github.com/Spekulucius/obsidian-brainhack/) but could not find it, I am not overly familiar with Github.

**Comment by Spekulucius** [comment]
No problem :) I appreciate every form of feedback.
Regarding the link you sent me, it leads to the homepage of my repo. From there you click on the folder "overrides", and should find the snippet.

If not, here is a direct link to the snippet.

https://github.com/Spekulucius/obsidian-brainhack/blob/main/overrides/brainhack-theme-greyscale-override.css

Regarding the shadows: Do you think they should be more visible (in light mode)?

**Comment by DutchPete** [comment]
Many thanks for that, I am very happy about it.

> Regarding the shadows: Do you think they should be more visible (in light mode)?

TBH, yes. But if you prefer to keep them the way they are, I can live with that.
BTW, my set up is: Live Preview 99.9% of the time, Light mode.

**Comment by Spekulucius** [comment]
Thanks for the feedback. I will look into that, maybe there is something I can do to make them more visible without them interrupting the feel the theme has atm.

best way to go would be to compare dark and light mode, as they have different color/transparency values, and adjust the shadows from there.

If I have some spare time, you could expect an update by this evening (gmt+2).

**Comment by DutchPete** [comment]
A listed blockquote as per you instructions above:

![image](https://github.com/user-attachments/assets/bea71b11-e136-4c25-be88-9cec9deff4f5)

That's not what you mean, right?

**Comment by Spekulucius** [comment]
I'm sorry, I forgot that you mainly use preview mode. Listed blockquotes (AFAIK) only work in reading mode :/

But how I make it work (in reading mode) is like this:

![Screenshot 2024-07-25 at 17 49 44](https://github.com/user-attachments/assets/65fd6bac-9283-4ee6-9731-59ed302bb707)

Also, I don't know if it is even possible to enable listed blockquotes in preview mode :/

**Comment by DutchPete** [comment]
OK, at least I know I did not do something wrong. I would love to have it in Preview mode too, but that evidently is an Obsidian thing rather than a Brainhack thing.

BTW, I check out you blockquotes in Reading mode: I love them.

I will not distract you anymore on this page. If there is a specific thing I'll open an issue.

**Comment by Spekulucius** [comment]
Love to hear that! Keep your eyes peeled for 1.4.
Also, I have an idea to implement listed blockquotes in preview mode, might check if that works...

And at last: Thank you for your support, it really helped me a lot!

**Comment by DutchPete** [comment]
Wow, version 1.4 is already out, beating your own targeted "within next couple of days".
Good work, well done 👍 and thank you.
